[build]
publish = "_site"
command = """
  curl -fsSL https://deno.land/install.sh | sh && \
  /opt/buildhome/.deno/bin/deno task build \
"""

[[redirects]]
from = "http://www.cao.sh/*"
to = "https://cao.sh/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.cao.sh/*"
to = "https://cao.sh/:splat"
status = 301
force = true
